name = "MyElementaryFunctions"
uuid = "2f3d21f5-896b-41ac-942e-479627e4f53b"
authors = ["suhui "]
version = "0.1.0"

[deps]
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"

[compat]
Polynomials = "3"